name: Deploy Dockerfile

on:
  push:
    branches:
      - main  
  pull_request:
      branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Stop docker
        run: docker stop ucn
      - name: Delete old container
        run: docker rm ucn
      - name: Pull repo from GitHub
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t ucn:docker .\
      - name: Start docker
        run: docker run --name ucn -d -p 8000:8000 ucn:docker