name: Deploy workflow
on:
  workflow_dispatch:

jobs:
    build:

         runs-on: self-hosted

         steps:
         - uses: actions/checkout@v3
         - name: Use Node.js 12.x
         - uses: actions/setup-node@v3
           with:
            node-version: 12.x
         - run: npm install
         - run: sudo node index.js &
